Repository HonHonX/Collection-Tracker, pull requests merged in 2025-01, with the labels that each got.

#59 Follow artist
  collectionTracker/collection/admin.py
  collectionTracker/collection/migrations/0017_alter_artist_id.py
  collectionTracker/collection/migrations/0018_alter_artist_id_userfollowedartists.py
  collectionTracker/collection/models.py
  collectionTracker/collection/urls.py
  collectionTracker/collection/views.py
  collectionTracker/db.sqlite3
  collectionTracker/static/css/styles.css
  collectionTracker/static/icons/follow.svg
  collectionTracker/static/icons/unfollow.svg
  collectionTracker/static/js/followArtist.js
  collectionTracker/static/js/manageAlbumState.js
  collectionTracker/tracker/templates/tracker/artist_overview.html
  collectionTracker/tracker/views.py
Labels: 💻backend, 🎨frontend, 🗝️database

#60 implment mail logic
  collectionTracker/collectionTracker/settings.py
  collectionTracker/collectionTracker/views.py
  collectionTracker/db.sqlite3
Labels: 💻backend

#63 Friends implementation
  collectionTracker/collection/templates/collection/album_detail.html
  collectionTracker/collection/templates/collection/album_overview.html
  collectionTracker/collection/templates/collection/wishlist_overview.html
  collectionTracker/collectionTracker/settings.py
  collectionTracker/collectionTracker/urls.py
  collectionTracker/db.sqlite3
  collectionTracker/friends/admin.py
  collectionTracker/friends/forms.py
  collectionTracker/friends/migrations/0001_initial.py
  collectionTracker/friends/migrations/0002_friend_status.py
  collectionTracker/friends/migrations/0003_alter_friend_name_alter_friend_status.py
  collectionTracker/friends/migrations/0004_friendlist.py
  collectionTracker/friends/migrations/0005_rename_email_friend_friend_email_and_more.py
  collectionTracker/friends/migrations/0006_sharingtoken.py
  collectionTracker/friends/models.py
  collectionTracker/friends/templates/friends/friends.html
  collectionTracker/friends/templates/friends/not_friends.html
  collectionTracker/friends/templates/friends/user_collection.html
  collectionTracker/friends/templates/friends/user_wishlist.html
  collectionTracker/friends/urls.py
  collectionTracker/friends/views.py
  collectionTracker/static/collection/css/collection.css
  collectionTracker/static/css/styles.css
  collectionTracker/static/friends/css/friends.css
  collectionTracker/static/icons/friends.svg
  collectionTracker/static/js/generateToken.js
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/sidebar.html
Labels: 💻backend, 🎨frontend, 🗝️database

#62 Implement search bar
  collectionTracker/collectionTracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/settings.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/urls.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/wsgi.cpython-312.pyc
  collectionTracker/db.sqlite3
  collectionTracker/home/templates/home/index.html
  collectionTracker/static/home/css/sidebar.css
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/sidebar.html
  collectionTracker/tracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/tracker/__pycache__/admin.cpython-312.pyc
  collectionTracker/tracker/__pycache__/apps.cpython-312.pyc
  collectionTracker/tracker/__pycache__/models.cpython-312.pyc
  collectionTracker/tracker/__pycache__/urls.cpython-312.pyc
  collectionTracker/tracker/__pycache__/views.cpython-312.pyc
  collectionTracker/tracker/migrations/__pycache__/__init__.cpython-312.pyc
  requirements.txt
Labels: 🎨frontend

#64 fix db and sidebar
  collectionTracker/db.sqlite3
  collectionTracker/templates/sidebar.html
Labels: 💻backend, 🎨frontend, 🗝️database

#65 User page implementation
  collectionTracker/collectionTracker/settings.py
  collectionTracker/collectionTracker/urls.py
  collectionTracker/db.sqlite3
  collectionTracker/home/admin.py
  collectionTracker/home/apps.py
  collectionTracker/home/forms.py
  collectionTracker/home/migrations/0001_initial.py
  collectionTracker/home/models.py
  collectionTracker/home/signals.py
  collectionTracker/home/templates/home/profile.html
  collectionTracker/home/urls.py
  collectionTracker/home/views.py
  collectionTracker/media/profile_images/Admin_20616857_1608627429181280_7134748708345308181_o.jpg
  collectionTracker/settings.py
  collectionTracker/static/home/css/profile.css
  collectionTracker/static/home/css/sidebar.css
  collectionTracker/static/img/default.jpg
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/sidebar.html
Labels: 💻backend, 🎨frontend, 🗝️database

#66 Settings page implemented
  collectionTracker/collectionTracker/urls.py
  collectionTracker/db.sqlite3
  collectionTracker/home/templates/home/index.html
  collectionTracker/home/templates/home/welcome.html
  collectionTracker/settings/admin.py
  collectionTracker/settings/apps.py
  collectionTracker/settings/migrations/0001_initial.py
  collectionTracker/settings/models.py
  collectionTracker/settings/signals.py
  collectionTracker/settings/templates/settings/settings.html
  collectionTracker/settings/urls.py
  collectionTracker/settings/views.py
  collectionTracker/static/css/autumn_theme.css
  collectionTracker/static/css/spring_theme.css
  collectionTracker/static/css/styles.css
  collectionTracker/static/css/summer_theme.css
  collectionTracker/static/css/winter_theme.css
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/base.html
  collectionTracker/templates/sidebar.html
Labels: 💻backend, 🎨frontend, 🗝️database

#67 Index followed artists implementation
  collectionTracker/collection/models.py
  collectionTracker/collection/urls.py
  collectionTracker/collection/views.py
  collectionTracker/collectionTracker/urls.py
  collectionTracker/db.sqlite3
  collectionTracker/home/templates/home/index.html
  collectionTracker/home/urls.py
  collectionTracker/home/views.py
  collectionTracker/media/profile_images/Admin_20616857_1608627429181280_7134748708345308181_o.jpg
  collectionTracker/media/profile_images/Admin_20988242_1626684157375607_4004902537094654399_o.jpg
  collectionTracker/settings/templates/settings/settings.html
  collectionTracker/static/css/styles.css
  collectionTracker/static/home/css/index.css
  collectionTracker/static/home/css/sidebar.css
  collectionTracker/static/icons/dashboard.svg
  collectionTracker/static/js/followArtist.js
  collectionTracker/static/js/navigation.js
  collectionTracker/static/js/selectColor.js
  collectionTracker/static/tracker/css/tracker.css
  collectionTracker/stats/templates/stats/dashboard.html
  collectionTracker/stats/urls.py
  collectionTracker/stats/views.py
  collectionTracker/templates/sidebar.html
  collectionTracker/tracker/templates/tracker/artist_overview.html
  collectionTracker/tracker/urls.py
  collectionTracker/tracker/views.py
Labels: 💻backend, 🎨frontend, 🗝️database

#68 Implement index page with followed artist logic
  collectionTracker/collection/migrations/0019_alter_album_artist.py
  collectionTracker/collection/models.py
  collectionTracker/collection/views.py
  collectionTracker/collectionTracker/urls.py
  collectionTracker/collectionTracker/views.py
  collectionTracker/db.sqlite3
  collectionTracker/home/admin.py
  collectionTracker/home/migrations/0002_userprofile.py
  collectionTracker/home/models.py
  collectionTracker/home/signals.py
  collectionTracker/home/templates/home/index.html
  collectionTracker/home/templates/home/profile.html
  collectionTracker/home/urls.py
  collectionTracker/home/views.py
  collectionTracker/media/profile_images/Admin_20988242_1626684157375607_4004902537094654399_o.jpg
  collectionTracker/media/profile_images/Admin_Brittany_Miraclebri2.jpg
  collectionTracker/settings/admin.py
  collectionTracker/settings/apps.py
  collectionTracker/settings/migrations/0002_delete_userprofile.py
  collectionTracker/settings/models.py
  collectionTracker/settings/signals.py
  collectionTracker/settings/urls.py
  collectionTracker/static/css/styles.css
  collectionTracker/static/home/css/index.css
  collectionTracker/static/home/css/profile.css
  collectionTracker/static/icons/follow.svg
  collectionTracker/static/icons/unfollow.svg
  collectionTracker/static/js/followArtist.js
  collectionTracker/static/js/manageAlbumState.js
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/sidebar.html
  collectionTracker/tracker/templates/tracker/artist_overview.html
Labels: 💻backend, 🎨frontend, 🗝️database

#69 update requirements
  requirements.txt
Labels: 💻backend

#71 Refactor css structure
  collectionTracker/collection/admin.py
  collectionTracker/collection/models.py
  collectionTracker/collection/templates/collection/album_detail.html
  collectionTracker/collection/templates/collection/album_overview.html
  collectionTracker/collection/templates/collection/blacklist_overview.html
  collectionTracker/collection/templates/collection/wishlist_overview.html
  collectionTracker/collection/views.py
  collectionTracker/db.sqlite3
  collectionTracker/friends/templates/friends/friends.html
  collectionTracker/friends/templates/friends/user_collection.html
  collectionTracker/friends/templates/friends/user_wishlist.html
  collectionTracker/home/templates/home/index.html
  collectionTracker/home/templates/home/profile.html
  collectionTracker/home/templates/home/welcome.html
  collectionTracker/home/views.py
  collectionTracker/static/css/apps/collection/album_detail.css
  collectionTracker/static/css/apps/friends/friends.css
  collectionTracker/static/css/apps/home/index.css
  collectionTracker/static/css/apps/home/profile.css
  collectionTracker/static/css/apps/home/welcome.css
  collectionTracker/static/css/apps/user/login_register.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/album_artist.css
  collectionTracker/static/css/components/button.css
  collectionTracker/static/css/components/form.css
  collectionTracker/static/css/components/icon.css
  collectionTracker/static/css/components/select.css
  collectionTracker/static/css/components/sidebar.css
  collectionTracker/static/css/layout.css
  collectionTracker/static/css/main.css
  collectionTracker/static/css/responsive.css
  collectionTracker/static/css/styles.css
  collectionTracker/static/css/themes/autumn_theme.css
  collectionTracker/static/css/themes/dark_mode.css
  collectionTracker/static/css/themes/spring_theme.css
  collectionTracker/static/css/themes/summer_theme.css
  collectionTracker/static/css/themes/winter_theme.css
  collectionTracker/static/home/css/welcome.css
  collectionTracker/static/js/manageAlbumState.js
  collectionTracker/static/js/navigation.js
  collectionTracker/static/tracker/css/tracker.css
  collectionTracker/static/tracker/js/script.js
  collectionTracker/stats/templates/stats/dashboard.html
  collectionTracker/templates/base.html
  collectionTracker/templates/base_with_sidebar.html
  collectionTracker/templates/sidebar.html
  collectionTracker/tracker/templates/tracker/artist_overview.html
  collectionTracker/tracker/urls.py
  collectionTracker/tracker/views.py
  collectionTracker/users/templates/registration/login.html
  collectionTracker/users/templates/registration/register.html
Labels: 🎨frontend

#72 implement slider
  collectionTracker/home/templates/home/index.html
  collectionTracker/static/css/apps/home/index.css
  collectionTracker/static/css/components/slider.css
  collectionTracker/static/css/layout.css
  collectionTracker/static/css/styles.css
  collectionTracker/static/js/albumSlider.js
Labels: 🎨frontend

#74 update badges
  collectionTracker/db.sqlite3
  collectionTracker/friends/templates/friends/friends.html
  collectionTracker/friends/views.py
  collectionTracker/home/templates/home/profile.html
  collectionTracker/static/css/apps/friends/friends.css
  collectionTracker/static/css/apps/home/profile.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/album_artist.css
  collectionTracker/stats/signals.py
  collectionTracker/templates/profile.html
Labels: 💻backend, 🎨frontend, 🗝️database

#75 fix URL for friends
  .gitignore
  collectionTracker/friends/views.py
  collectionTracker/home/templates/home/welcome.html
  collectionTracker/static/css/apps/home/welcome.css
Labels: 💻backend, 🎨frontend, 🗝️database

#76 update signals
  .gitignore
  collectionTracker/collection/apps.py
  collectionTracker/collection/models.py
  collectionTracker/collection/signals.py
  collectionTracker/collectionTracker/settings.py
  collectionTracker/db.sqlite3
  collectionTracker/friends/templates/friends/user_collection.html
  collectionTracker/friends/templates/friends/user_wishlist.html
  collectionTracker/stats/signals.py
  collectionTracker/stats/templates/stats/dashboard.html
  collectionTracker/stats/views.py
Labels: 💻backend

#77 fix badges
  collectionTracker/stats/signals.py
Labels: 💻backend

#83 Badge notification implementation
  collectionTracker/collection/templates/collection/album_overview.html
  collectionTracker/collection/templates/collection/artist_overview.html
  collectionTracker/collection/templates/collection/blacklist_overview.html
  collectionTracker/collection/templates/collection/index.html
  collectionTracker/collection/templates/collection/wishlist_overview.html
  collectionTracker/collection/urls.py
  collectionTracker/collection/views.py
  collectionTracker/collectionTracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/settings.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/urls.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/wsgi.cpython-312.pyc
  collectionTracker/collectionTracker/settings.py
  collectionTracker/error.log
  collectionTracker/static/css/apps/users/profile.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/album_artist.css
  collectionTracker/static/css/components/icon.css
  collectionTracker/static/css/components/select.css
  collectionTracker/static/icons/remove.svg
  collectionTracker/static/js/manageAlbumState.js
  collectionTracker/static/js/temp.js
  collectionTracker/static/js/updateProgressBars.js
  collectionTracker/stats/admin.py
  collectionTracker/stats/migrations/0004_notification.py
  collectionTracker/stats/models.py
  collectionTracker/stats/signals.py
  collectionTracker/stats/urls.py
  collectionTracker/stats/views.py
  collectionTracker/templates/base.html
  collectionTracker/utils/stats_helpers.py
  requirements.txt
Labels: 💻backend, 🎨frontend, 🗝️database

#86 fix date error
  collectionTracker/integration/spotify_query.py
  requirements.txt
Labels: 💻backend

#84 mobile-version stats, friends, profile
  collectionTracker/collectionTracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/settings.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/urls.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/wsgi.cpython-312.pyc
  collectionTracker/media/profile_images/Marius_Image.png
  collectionTracker/static/css/apps/friends/friends.css
  collectionTracker/static/css/apps/stats/stats.css
  collectionTracker/static/css/apps/users/profile.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/button.css
  collectionTracker/static/css/components/form.css
  collectionTracker/static/css/components/sidebar.css
  collectionTracker/static/css/layout.css
  collectionTracker/templates/sidebar.html
Labels: 🎨frontend

#89 add predictions
  collectionTracker/collection/templates/collection/album_detail.html
  collectionTracker/collectionTracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/wsgi.cpython-312.pyc
  collectionTracker/error.log
  collectionTracker/static/js/showPriceGraph.js
  collectionTracker/stats/urls.py
  collectionTracker/stats/views.py
Labels: 💻backend, 🎨frontend

#91 mobile_bar
  collectionTracker/error.log
  collectionTracker/static/css/apps/collection/index.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/sidebar.css
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/base.html
  collectionTracker/templates/base_with_sidebar.html
  collectionTracker/templates/sidebar.html
Labels: 🎨frontend

#93 mobile implementation
  collectionTracker/collection/templates/collection/artist_overview.html
  collectionTracker/collectionTracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/wsgi.cpython-312.pyc
  collectionTracker/static/css/apps/collection/album_detail.css
  collectionTracker/static/css/apps/collection/artist_detail.css
  collectionTracker/static/css/apps/collection/index.css
  collectionTracker/static/css/components/album_artist.css
  collectionTracker/static/css/components/button.css
  collectionTracker/static/css/components/form.css
  collectionTracker/static/css/components/gauge.css
  collectionTracker/static/css/layout.css
  collectionTracker/static/css/responsive.css
  collectionTracker/templates/base_with_sidebar.html
Labels: 🎨frontend

#95 Mobile adjustments
  collectionTracker/static/css/apps/collection/album_detail.css
  collectionTracker/static/css/apps/collection/artist_detail.css
  collectionTracker/static/css/apps/friends/friends.css
  collectionTracker/static/css/apps/stats/stats.css
  collectionTracker/static/css/apps/users/login_register.css
  collectionTracker/static/css/apps/users/profile.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/album_artist.css
  collectionTracker/static/css/components/button.css
  collectionTracker/static/css/components/form.css
  collectionTracker/static/css/components/progress_counter.css
  collectionTracker/static/css/components/sidebar.css
  collectionTracker/static/css/components/slider.css
  collectionTracker/static/css/layout.css
  collectionTracker/static/js/navigation.js
  collectionTracker/templates/sidebar.html
  collectionTracker/users/templates/users/change_password.html
  collectionTracker/users/templates/users/profile.html
Labels: 🎨frontend

#98 Final adaption mobile
  collectionTracker/collectionTracker/__pycache__/__init__.cpython-312.pyc
  collectionTracker/collectionTracker/__pycache__/wsgi.cpython-312.pyc
  collectionTracker/static/css/apps/collection/album_detail.css
  collectionTracker/static/css/apps/collection/artist_detail.css
  collectionTracker/static/css/apps/collection/index.css
  collectionTracker/static/css/apps/collection/wishlist_overview.css
  collectionTracker/static/css/apps/stats/stats.css
  collectionTracker/static/css/apps/users/login_register.css
  collectionTracker/static/css/apps/users/profile.css
  collectionTracker/static/css/apps/users/welcome.css
  collectionTracker/static/css/base.css
  collectionTracker/static/css/components/album_artist.css
  collectionTracker/static/css/components/button.css
  collectionTracker/static/css/components/form.css
  collectionTracker/static/css/components/gauge.css
  collectionTracker/static/css/components/image_carousel.css
  collectionTracker/static/css/components/notification.css
  collectionTracker/static/css/components/progress_counter.css
  collectionTracker/static/css/components/select.css
  collectionTracker/static/css/components/sidebar.css
  collectionTracker/static/css/components/slider.css
  collectionTracker/static/css/layout.css
  collectionTracker/static/css/main.css
  collectionTracker/static/css/responsive.css
  collectionTracker/static/js/albumDetail.js
  collectionTracker/static/js/albumSlider.js
  collectionTracker/static/js/imageCarousel.js
  collectionTracker/static/js/navigation.js
  collectionTracker/static/js/notification.js
  collectionTracker/static/js/update_first_name.js
  collectionTracker/static/js/update_last_name.js
  collectionTracker/templates/base.html
Labels: 🎨frontend

#100 Feature update
  collectionTracker/collectionTracker/settings.py
  collectionTracker/static/js/manageAlbumState.js
  collectionTracker/stats/signals.py
  requirements.txt
Labels: 💻backend, 🎨frontend

#101 Fix merge conflict
  collectionTracker/collection/templates/collection/album_detail.html
  collectionTracker/collection/templates/collection/album_overview.html
  collectionTracker/collection/views.py
  collectionTracker/collectionTracker/settings.py
  collectionTracker/error.log
  collectionTracker/integration/discogs_query.py
  collectionTracker/integration/price.py
  collectionTracker/integration/spotify_query.py
  collectionTracker/static/css/apps/collection/album_detail.css
  collectionTracker/static/css/apps/collection/artist_detail.css
  collectionTracker/static/css/apps/users/change_password.css
  collectionTracker/static/css/apps/users/profile.css
  collectionTracker/static/css/components/icon.css
  collectionTracker/static/icons/show.svg
  collectionTracker/static/js/imageCarousel.js
  collectionTracker/static/js/navigation.js
  collectionTracker/stats/signals.py
  collectionTracker/templates/base.html
  collectionTracker/templates/sidebar.html
  collectionTracker/update_db.py
  collectionTracker/users/templates/users/change_password.html
  requirements.txt
Labels: bug, 💻backend, 🎨frontend, 🗝️database
